%\VignetteIndexEntry{mRMRe: an R package for parallelized mRMR ensemble feature selection}
%\VignetteDepends{Rcpp,xtable}
%\VignetteSuggests{}
%\VignetteKeywords{}
%\VignettePackage{mRMRe}

\documentclass[12pt]{article}

\usepackage[utf8]{inputenc}
\usepackage{authblk}


\title{mRMRe: an R package for parallelized mRMR ensemble feature selection}
\author[1]{Nicolas De Jay}
\author[1]{Simon Papillon-Cavanagh}
\author[2]{Catharina Olsen}
\author[2]{Gianluca Bontempi}
\author[1]{Benjamin Haibe-Kains}
\affil[1]{Bioinformatics and Computational Biology Laboratory, Institut de recherches cliniques de Montr\'{e}al, Montreal, Quebec, Canada}
\affil[2]{Machine Learning Group, Universit\'{e} Libre de Bruxelles, Brussels, Belgium}

\SweaveOpts{highlight=TRUE, tidy=TRUE, keep.space=TRUE, keep.blank.space=FALSE, keep.comment=TRUE}

<<setup,echo=FALSE,results=hide>>=
options(keep.source=TRUE)
@

\begin{document}


\maketitle
\tableofcontents

%------------------------------------------------------------
\section{Introduction}
%------------------------------------------------------------

\textit{mRMRe} is an R package for parallelized mRMR ensemble feature selection.

%------------------------------------------------------------
\subsection{Installation}
%------------------------------------------------------------

\textit{mRMRe} requires that \textit{Rcpp} is installed. 
These should be installed automatically when you install \textit{mRMRe}. To install \textit{mRMRe}, source biocLite from CRAN.

<<install-pkg, eval=false>>=
install.packages("mRMRe")
@

Load \textit{mRMRe} into your current workspace:
<<loadlib,results=hide>>==
library(mRMRe)
@ 

Load the example dataset \textit{cgps} into your current workspace:
<<loadlib,results=hide>>==
data(cgps)
@

%------------------------------------------------------------
\section{Measures of Associtation}
%------------------------------------------------------------

%------------------------------------------------------------
\subsection{Mutual Information Matrix}
%------------------------------------------------------------

<<eval=FALSE>>=
merged_data <- data.frame(ic50=cgps_ic50, cgps_ge)

# Pearson correlation for continuous variables
mim.pearson <- build.mim(data=merged_data, uses_ranks=FALSE)

# Spearman correlation for continuous variables
mim.spearman <- build.mim(data=merged_data) 
@

%------------------------------------------------------------
\subsection{Correlations}
%------------------------------------------------------------

Correlations

%------------------------------------------------------------
\section{mRMR Feature Selection}
%------------------------------------------------------------

%------------------------------------------------------------
\subsection{Classic mRMR}
%------------------------------------------------------------

Classic

%------------------------------------------------------------
\subsection{Ensemble mRMR}
%------------------------------------------------------------

Ensemble

\end{document}